name = "api"
main = "src/index.ts"
compatibility_date = "2023-04-27"
[vars]
LIBSQL_DB_URL = "libsql://my-db-sattwyk.turso.io"
LIBSQL_AUTH_TOKEN = "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODI1OTcxNjgsImlkIjoiZjQ1ZGQxN2UtZTRmMi0xMWVkLWI3YjAtYzIyZmFjNzE2ODUwIn0.rklWbDc3qUdRtlRaZnWidWbM9XUsM6WZDcjcaM-KAMP8-Q3TpQpnx8izuMJxjimLd50oty3urWdve3H"